version: "3.9"

services:
  sensnow-db:
    image: postgres
    container_name: sensnow-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - pgdata:/data/postgres

  sensnow-app:
    build: .
    container_name: sensnow-app
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/server/sensnow-api
    links:
      - sensnow-db
    depends_on:
      - sensnow-db

volumes:
  pgdata:
    driver: local
