version: "3.9"

services:
  amawfinance-db:
    image: postgres
    container_name: amawfinance-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - pgdata:/data/postgres

  amawfinance-app:
    build: .
    container_name: amawfinance-app
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/server/amawfinance-api
    links:
      - amawfinance-db
    depends_on:
      - amawfinance-db

volumes:
  pgdata:
    driver: local
